### ISSUE TITLE
syntax error in example in README?

### ISSUE THREAD

**Issue by luofanghao** [venmo/business-rules#50]
'''py
rules = [
# expiration_days < 5 AND current_inventory > 20
{ "conditions": { "all": [
      { "name": "expiration_days",
        "operator": "less_than",
        "value": 5,
      },
      { "name": "current_inventory",
        "operator": "greater_than",
        "value": 20,
      },
  ]},
  "actions": [
      { "name": "put_on_sale",
        "params": {"sale_percentage": 0.25},
      },
  ],
},

# current_inventory < 5 OR (current_month = "December" AND current_inventory < 20)
{ "conditions": { "any": [
      { "name": "current_inventory",
        "operator": "less_than",
        "value": 5,
      },
    ]},
      { "all": [
        {  "name": "current_month",
          "operator": "equal_to",
          "value": "December",
        },
        { "name": "current_inventory",
          "operator": "less_than",
          "value": 20,
        }
      ]},
  },
  "actions": [
    { "name": "order_more",
      "params":{"number_to_order": 40},
    },
  ],
}]
'''

some syntax alert in the 'conditions' part.

**Comment by prav1234567** [comment]
there are extra ',' in the json. try doing it. :P

**Comment by vishnu-dev** [comment]
How do we fix this? I'm not able to figure out nested conditions.

**Comment by bharat-Kundapur** [comment]
@luofanghao try this rule definition and let me know if it works. 

```
[

{"conditions": {"all": [
    {"name": "expiration_days",
     "operator": "less_than",
     "value": 5
     },
    {"name": "current_inventory",
     "operator": "greater_than",
     "value": 20
     }
]},
    "actions": [
        {"name": "put_on_sale",
         "params": {"sale_percentage": 0.25}
         }
    ]
},


{"conditions": {"any": [
    {"name": "current_inventory",
     "operator": "less_than",
     "value": 5
     }
],
    "all": [
        {"name": "current_month",
         "operator": "equal_to",
         "value": "December"
         },
        {"name": "current_inventory",
         "operator": "less_than",
         "value": 20
         }
    ]}
},
{"actions": [
    {"name": "order_more",
     "params": {"number_to_order": 40}
     }
]
}]
```

**Comment by Eduard-gan** [comment]
it doesnt
```
Traceback (most recent call last):
  File "RULES.py", line 103, in <module>
    result = run_all(
             ^^^^^^^^
  File "/.virtualenvs/reception/lib/python3.11/site-packages/business_rules/engine.py", line 10, in run_all
    result = run(rule, defined_variables, defined_actions)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.virtualenvs/reception/lib/python3.11/site-packages/business_rules/engine.py", line 18, in run
    conditions, actions = rule['conditions'], rule['actions']
                                              ~~~~^^^^^^^^^^^
KeyError: 'actions'
```

Try this:

```
rules = [
    # expiration_days < 5 AND current_inventory > 20
    {
        "conditions": {
            "all": [
                { "name": "expiration_days", "operator": "less_than", "value": 5 },
                { "name": "current_inventory", "operator": "greater_than", "value": 20 },
            ]
        },
        "actions": [
            { "name": "put_on_sale", "params": {"sale_percentage": 0.25} },
        ],
    },

    # current_inventory < 5 OR (current_month = "December" AND current_inventory < 20)
    {
        "conditions": {
            "any": [
                { "name": "current_inventory", "operator": "less_than", "value": 5 },
                {
                    "all": [
                        { "name": "current_month", "operator": "equal_to", "value": "December" },
                        { "name": "current_inventory", "operator": "less_than", "value": 20 }
                    ]
                }
            ]
        },
        "actions": [
            { "name": "order_more", "params": {"number_to_order": 40} }
        ]
    }
]
```
